# Site settings
title: ava nemanic
description: 'Personal Website'
url: 'http://avanemanic.com'
baseurl: ''
profilepic: '/images/yeet.png'
bkimage: '/images/IMG_7022.JPG'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Ava Nemanic'
  email: avanemanic@gmail.com
#  twitter_username: thomzuehlke
#  facebook_username: joshgerdes
  github_username:  avanemanic
  linkedin_username:  avanemanic
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
